### ISSUE TITLE
hearthspeak won't launch??

### ISSUE THREAD

**Issue by eggwhich** [evfredericksen/HearthSpeak#2]
<img width="688" alt="hearth" src="https://user-images.githubusercontent.com/43306104/45591739-0f499880-b94a-11e8-8074-82e592866e37.png">
I'm not sure why it will not launch because my computer is very new, I have an HP laptop. I have even allowed hearthspeak through my Windows firewall's. It launches for 2 seconds with this error message , that's it. Thank you for your help!

**Comment by evfredericksen** [comment]
That error will occur if you haven't run Hearthstone on your machine yet. Should be good after launching it once.

**Comment by etfre** [comment]
Thanks for the kind words! It's very rewarding/motivating to see other people using this program. I have occasional issues with RSI in my hands and I know how frustrating it is to not be able to play games as a result.

**Comment by eggwhich** [comment]
Yes! That is a bummer. I understand your pain too! Hand problems are
literally the worst!!! Thanks so much for again for making this ❤
